version: "3.9"
services:
  nestjs-server:
    depends_on:
      mysqldb:
        condition: service_healthy
        restart: true
    build:
      context: .
      dockerfile: dockerfile
      target: development
    container_name: repm-server
    command: npm run start
    restart: unless-stopped
    volumes:
      - app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    expose:
      - 3000
    stdin_open: true
    tty: true
    networks:
      - default

  mysqldb:
    image: mysql
    container_name: repm-db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - default
    environment:
      MYSQL_DATABASE: "repm"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "test"
      # You can use whatever password you like
      MYSQL_PASSWORD: "test_user_pwd"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 40
    ports:
      - "3306:3306"
    expose:
      - 3306

volumes:
  db_data:
  app:

networks:
  default:
